config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
      resources :products do
        get 'add_on_maker_variants' => 'add_on_maker_variants#index'
        resources :variants do
          resources :add_on_maker_variants do
        end
      end
    end
  end
end

app/models/spree/ability_decorator.rb
class AbilityDecorator
  include CanCan::Ability
  def initialize(user)

    if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
      can [:admin, :index, :read, :update, :edit], Spree::AddOnMakerVariant
    end
  end
end

Spree::Ability.register_ability(AbilityDecorator)

app/models/spree/add_on_maker_variant.rb
module Spree
  class AddOnMakerVariant < ActiveRecord::Base
    belongs_to :variant, class_name: 'Spree::Variant', :foreign_key => :variant_id
    belongs_to :product, class_name: 'Spree::Product'
    after_initialize :set_defaut_value

    validates :article_number, length: {maximum: 13}, allow_nil: true


    validates :list_price_amount, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
    validates :min_price_amount,  numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

  private
    def set_defaut_value
      self.list_price_currency = Spree::Config[:currency]  if self.new_record?
      self.min_price_currency = Spree::Config[:currency]   if self.new_record?
    end 

  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
  has_many :add_on_maker_variants, :through => :variants

#   enable products to CRUD each own add_on_maker_variants by accept nesting as child
  accepts_nested_attributes_for :add_on_maker_variants, allow_destroy: true

  end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    has_one :add_on_maker_variant, class_name: 'Spree::AddOnMakerVariant'

#   builds add_on_maker_variants from created variant ids
    after_create :create_add_on_maker_variants_from_variants

#   enable variants to CRUD each own add_on_maker_variants by accept nesting as child
    accepts_nested_attributes_for :add_on_maker_variant, allow_destroy: true

    def create_add_on_maker_variants_from_variants
      Spree::AddOnMakerVariant.where(variant_id: self.id).first_or_initialize do |a|
        a.variant_id = self.id
        a.list_price_currency = Spree::Config[:currency]  if a.list_price_currency.blank?
        a.min_price_currency = Spree::Config[:currency]   if a.min_price_currency.blank?
        a.save!
      end
    end

  end
end

app/controllers/spree/admin/add_on_maker_variants_controller.rb
module Spree
  module Admin
   class AddOnMakerVariantsController < ResourceController
      before_filter :load_data, :except => [:index]

      def show
        session[:return_to] ||= request.referer
        redirect_to( :action => :edit )
      end

      def index
        session[:return_to] = request.url
        @product = Spree::Product.where(:permalink => params[:product_id]).includes(:add_on_makers).first

        if @product.has_variants?
          @variant = @product.variants
        else
          @variant = Spree::Variant.where(:id => @product.master.id)
        end

        @add_on_maker_variant = Spree::AddOnMakerVariant.where(:variant_id => @variant).page(params[:page])
        render :index
      end

      def edit
        session[:return_to] = request.url
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @add_on_maker_variant = Spree::AddOnMakerVariant.where(:variant_id => params[:variant_id]).first_or_initialize
        render :edit
      end

      def create
        @add_on_maker_variant = Spree::AddOnMakerVariant.new(add_on_maker_variant_params.merge(:variant_id => params[:variant_id]))
        respond_to do |format|
          if @add_on_maker_variant.save
            flash[:success] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_created')
            format.html { redirect_to admin_product_variant_add_on_maker_variants_path }
            format.json { render action: 'index', status: :created, location: @add_on_maker_variant }
          else
            flash[:error] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_has_error')
            format.html { render action: 'new' }
            format.json { render json: @add_on_maker_variant.errors }
          end
        end
      end

      def update
        respond_to do |format|
          if @add_on_maker_variant.update(add_on_maker_variant_params)
            flash[:success] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_updated')
            format.html { redirect_to :action => :index }
            format.json { head :no_content }
          else
            flash[:error] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_has_error')
            format.html { render action: 'edit' }
            format.json { render json: @add_on_maker_variant.errors }
          end
        end
      end

      def destroy
        @variant = Spree::Variant.find(params[:id])
        if @variant.destroy
          flash[:success] = Spree.t('notice_messages.variant_deleted')
        else
          flash[:success] = Spree.t('notice_messages.variant_not_deleted')
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_maker_variant_path(params[:product_id]) }
          format.js  { render_js_for_destroy }
        end
      end

  protected
      def variant_includes
        [:add_on_maker_variants]
      end

      def load_data
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @taxons = Taxon.order(:name)
        @option_types = OptionType.order(:name)
        @tax_categories = TaxCategory.order(:name)
        @shipping_categories = ShippingCategory.order(:name)
      end

  private
      def permit_attributes
        params.require(:add_on_maker_variant).permit!
      end

      def add_on_maker_variant_params
        params.require(:add_on_maker_variant).permit(:article_number, :list_price_amount, :list_price_currency, :min_price_amount, :min_price_currency, :is_discontinued)
      end

    end
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  private
      def product_params
        params.require(:product).permit(add_on_maker_variant_attributes: [ :artice_number, :list_price_amount, :list_price_currency, :min_price_amount, :min_price_currency, :is_discontinued])
      end
end

app/controllers/spree/admin/variants_controller_decorator.rb
Spree::Admin::VariantsController.class_eval do
  before_filter :load_add_on_maker_variant, :only => :load_data

  def load_add_on_maker_variant
logger.info "##load_add_on_maker_variant##"
    @add_on_maker_variant = Spree::AddOnMakerVariant.where(:id => params[:id]).first
logger.info @add_on_maker_variant
  end

  private
      def variant_params
        params.require(:variant).permit(add_on_maker_variant_attributes: [ :artice_number, :list_price_amount, :list_price_currency, :min_price_amount, :min_price_currency, :is_discontinued])
      end
end

app/helpers/spree/admin/products_helper_decorator.rb
Spree::Admin::ProductsHelper.class_eval do
      def add_on_makers_options_for(product)
        options = @add_on_makers.map do |add_on_maker|
          selected = product.add_on_makers.include?(add_on_maker)
          content_tag(:option,
                      :value    => add_on_maker.id,
                      :selected => ('selected' if selected)) do
            add_on_maker.name
          end
        end.join("").html_safe
      end
end

app/views/spree/admin/add_on_maker_variants/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Maker Variants'} %>

<% content_for :page_title do %>
  : <%= @add_on_maker_variant.variant.sku %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('add_on.back_to_product_add_on_maker_variants_list'), admin_product_variant_add_on_maker_variants_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= form_for [:admin, @product, @variant, @add_on_maker_variant], url: admin_product_variant_add_on_maker_variant_path(:variant_id => params[:variant_id], :id => params[:id]) do |f| %>
  <div data-hook="admin_inside_add_on_maker_variant_form" class="row">
    <div class='alpha six columns'>

      <%= f.field_container :article_number do %>
          <%= f.label :article_number, t('activerecord.attributes.add_on_maker_variant.article_number') %>
          <%= f.text_field :article_number, :class => 'fullwidth', :autofocus => true %>
          <%= f.error_message_on :article_number %>
      <% end %>


        <div class="alpha three columns">
      <%= f.field_container :list_price_amount do %>
          <%= f.label :list_price_amount, t('activerecord.attributes.add_on_maker_variant.list_price_amount') %>
          <%= f.text_field :list_price_amount, :class => 'fullwidth' %>
          <%= f.error_message_on :list_price_amount %>
      <% end %>
        </div>

        <div class="omega three columns">
      <%= f.field_container :list_price_currency do %>
          <%= f.label :list_price_currency, t('activerecord.attributes.add_on_maker_variant.list_price_currency') %>
          <%= f.text_field :list_price_currency, :class => 'fullwidth' %>
          <%= f.error_message_on :list_price_currency %>
      <% end %>
        </div>

        <div class="alpha three columns">
    <%= f.field_container :min_price_amount do %>
        <%= f.label :min_price_amount, t('activerecord.attributes.add_on_maker_variant.min_price_amount') %>
        <%= f.text_field :min_price_amount, :class => 'fullwidth' %>
        <%= f.error_message_on :min_price_amount %>
    <% end %>
        </div>

        <div class="omega three columns">
    <%= f.field_container :min_price_currency do %>
        <%= f.label :min_price_currency, t('activerecord.attributes.add_on_maker_variant.min_price_currency') %>
        <%= f.text_field :min_price_currency, :class => 'fullwidth' %>
        <%= f.error_message_on :min_price_currency %>
    <% end %>
        </div>
    <div class="clear"></div>
    </div>
    <div class='omega six columns'>
    <%= f.field_container :is_discontinued do %>
        <%= f.label :is_discontinued, t('activerecord.attributes.add_on_maker_variant.is_discontinued') %>
        <%= f.check_box :is_discontinued, :class => 'fullwidth' %>
        <%= f.error_message_on :is_discontinued %>
    <% end %>
    </div>
  </div>


  <%= f.submit %>

  </div>
<% end %>

app/views/spree/admin/add_on_maker_variants/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Maker Variants'} %>

<% content_for :page_title do %>
  <%= t("add_on.listing_add_on_maker_variant") %>
<% end %>

<% if @product.add_on_makers.blank? %>

  <%= t("add_on.this_product_does_not_have_any_add_on_maker") %><br>
  <%= link_to t("add_on.please_set_add_on_maker_to_product"), edit_admin_product_path(:id => params[:product_id]) %>

<% else %>

<%= paginate @add_on_maker_variant %>

<table class='index'>
  <thead>
    <tr>
      <th><%= t("activerecord.attributes.variant.id") %></th>
      <th><%= Spree.t(:options) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:sku) %></th>
    </tr>
  </thead>
  
  <tbody>
    <% for variant in @variant %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= variant.id %></td>
        <td class="align-center"><%= variant.options_text %></td>
        <td class="align-center"><%= variant.price %></td>
        <td class="align-center"><%= variant.sku %></td>

        <% if variant.add_on_maker_variant.blank? %>
        <td class="actions"><%= link_to t("edit"), ("/admin/products/" + params[:product_id] + "/variants/#{variant.id}/add_on_maker_variants/new") , :class => 'edit' %></td>
        <% else %>
        <td class="actions"><%= link_to t("edit"), ("/admin/products/" + params[:product_id] + "/variants/#{variant.id}/add_on_maker_variants/#{variant.add_on_maker_variant.id}/edit") , :class => 'edit' %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/spree/admin/add_on_maker_variants/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Maker Variants'} %><% content_for :page_title do %>
  <%= t('add_on.add_on_maker_variant') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('add_on.back_to_product_add_on_maker_variants_list'), admin_product_add_on_maker_variants_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= form_for [:admin, @product, @variant, @add_on_maker_variant], url: admin_product_variant_add_on_maker_variants_path(:variant_id => params[:variant_id]) do |f| %>
  <div data-hook="admin_inside_add_on_maker_variant_form" class="row">
    <div class='alpha six columns'>
      <%= f.field_container :article_number do %>
          <%= f.label :article_number, t('activerecord.attributes.add_on_maker_variant.article_number') %>
          <%= f.text_field :article_number, :class => 'fullwidth', :autofocus => true %>
          <%= f.error_message_on :article_number %>
      <% end %>


        <div class="alpha three columns">
      <%= f.field_container :list_price_amount do %>
          <%= f.label :list_price_amount, t('activerecord.attributes.add_on_maker_variant.list_price_amount') %>
          <%= f.text_field :list_price_amount, :class => 'fullwidth' %>
          <%= f.error_message_on :list_price_amount %>
      <% end %>
        </div>

        <div class="omega three columns">
      <%= f.field_container :list_price_currency do %>
          <%= f.label :list_price_currency, t('activerecord.attributes.add_on_maker_variant.list_price_currency') %>
          <%= f.text_field :list_price_currency, :class => 'fullwidth' %>
          <%= f.error_message_on :list_price_currency %>
      <% end %>
        </div>


        <div class="alpha three columns">
    <%= f.field_container :min_price_amount do %>
        <%= f.label :min_price_amount, t('activerecord.attributes.add_on_maker_variant.min_price_amount') %>
        <%= f.text_field :min_price_amount, :class => 'fullwidth' %>
        <%= f.error_message_on :min_price_amount %>
    <% end %>
        </div>

        <div class="omega three columns">
    <%= f.field_container :min_price_currency do %>
        <%= f.label :min_price_currency, t('activerecord.attributes.add_on_maker_variant.min_price_currency') %>
        <%= f.text_field :min_price_currency, :class => 'fullwidth' %>
        <%= f.error_message_on :min_price_currency %>
    <% end %>
        </div>

    </div>
    <div class='omega six columns'>
    <%= f.field_container :is_discontinued do %>
        <%= f.label :is_discontinued, t('activerecord.attributes.add_on_maker_variant.is_discontinued') %>
        <%= f.check_box :is_discontinued, :class => 'fullwidth' %>
        <%= f.error_message_on :is_discontinued %>
    <% end %>
    </div>
  </div>

      <%= f.submit %>

  </div>
<% end %>